// /app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display, Poetsen_One, Space_Grotesk, } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
// import { CursorProvider } from "./cursor/CursorContext";
import CustomCursor from "./cursor/cursor";
import PageTransitionWrapper from "@/app/components/PageTransitionWrapper"; // ✅ client wrapper for pages transition


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// เรียกใช้ฟอนต์ พร้อมตั้งชื่อ variable
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  weight: ["400", "700"], // เลือกน้ำหนักตามต้องการ

});

const poetsen = Poetsen_One({
  subsets: ["latin"],
  variable: "--font-poetsen",
  weight: ["400","400"],
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-spacegrotesk"
})

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={`${poetsen.variable} ${playfair.variable} ${spaceGrotesk.variable}`}>
      <Header />
      <CustomCursor/>
        {/* <CursorProvider> */}
          {/* ✅ ใส่ PageTransitionWrapper */}
          <PageTransitionWrapper>
            {children}
          </PageTransitionWrapper>
        {/* </CursorProvider> */}
        <Footer />
      </body>
    </html>
  );
}