import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import { CursorProvider } from "./cursor/CursorContext";
import CustomCursor from "./cursor/cursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
        // สามารถทีั่จะใส่โค้ดเต็มๆลงไปได้เลยหรือจะเชื่อม path แบบนี้ก็ได้
    <html lang="en">
      <body>
        <Header />
        <CursorProvider>{children}</CursorProvider>
        <Footer />

      </body>
    </html>
  );
}
